### ISSUE TITLE
Google API 데이터 파싱 테스트

### ISSUE THREAD

**Issue by Ninetag-ktk** [Ninetag-ktk/FinalProject#17]
1. People 과 Calender build 하는 것 한번에 가능한지 (Scope)
2. 현재 flow에서 사용되고 있는 토큰의 저장 방식을 변경할 수 있는지 (String이나 Session, Cookie 등에 담을 수 있는지)
3. 데이터 파싱 해서 Attribute에 담고, 테스트 페이지에서 출력할 수 있는지
4. (파싱한 데이터 Attribute에 담아서 쿼리문 연결해서 SQL 할 수 있는지)

**Comment by seorema** [comment]
1. scope에 같이 적어놓으면 가능함
private static final List<String> SCOPES = Arrays.asList(PeopleServiceScopes.USERINFO_PROFILE, CalendarScopes.CALENDAR_EVENTS)
