### ISSUE TITLE
구글 캘린더 API R&D

### ISSUE THREAD

**Issue by Ninetag-ktk** [Ninetag-ktk/FinalProject#4]

**Comment by Ninetag-ktk** [comment]
예시 코드를 활용하여 연결 되는 것 확인
&
데이터 get 되는 것 확인
---
이후 parsing을 위한 R&D 진행 필요

**Comment by seorema** [comment]
1. Calender api를 통해 일정(Events)을 가져오는 코드 작성이 목표(데이터 베이스에 넣어야 하므로)

                   List<Event> items = events.getItems(); // Events를 쪼개서 Event타입의 리스트에 넣음
                    for (Event event : items) { // 각 이벤트를 하나씩 살펴보기
                        DateTime start = event.getStart().getDateTime(); // 이벤트가 시작되는 시간을 start로 설정
                        if (start == null) {
                            start = event.getStart().getDate(); // 만약 따로 설정되어 있지 않으면 이벤트가 있는 날짜를 시작시간으로 설정
                        }
                        System.out.printf("%s (%s)\n", event.getDescription(), start); // 
                    
2. 문제점 = 코드 문제로 일정을 가져올 때 '할 일'이라는 일정이 안가져와짐 

3.문제의 이유 = Calendar api는 Calendarid로 각 캘린더들이 구분되어 있는데 primary라는 것은 '기본 캘린더'만 가져옴

                        Events events = service.events().list("primary")

   해결방안 = CalendarList를 통해 Calendarid를 구해서 primary라는 요소를 대체함

            CalendarList calendarList = service.calendarList().list().setPageToken(pageToken).execute();// 캘린더 리스트를 받아오는 명령어
            List<CalendarListEntry> items1 = calendarList.getItems(); // 캘린더리스트들을 리스트형태의 CalendarListEntry로 변환시킨 것
            for (CalendarListEntry calendarListEntry : items1) { // 각 items안에 있는 캘린더리스트의 캘린더들을 하나씩 가져오는 것
                Events events = service.events().list(calendarListEntry.getId()) // 각 캘린더들의 id를 기준으로 뽑아옴(문제해결법)

4. 이후 CalendarList가 포함된 코드가 추가됨

5. 결과 요약 (코드 내용을 간추려서 / 각 코드의 기능=역할을 설명)

**Comment by Ninetag-ktk** [comment]
정리 요령
1. 하고자 했던 것 (필요한 것과 필요한 이유)
2. 할 때 발생했던 문제 (지금의 경우, 캘린더의 primary만 불러와지는 문제 = [할 일]이 가져와지지 않았음)
3. 문제가 발생한 원리 및 해결 방법(방식)
4. 해결 이후 하고자 했던 것에서 추가된(추가되어야 했던) 내용
5. 결과 요약 (코드 내용을 간추려서 / 각 코드의 기능=역할을 설명)
